include: package:flutter_lints/flutter.yaml

linter:
  rules:
    require_trailing_commas: true
    always_use_package_imports: true

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - '**/*.g.dart'
    - lib/base/networking/apis/tumdev/campus_backend.pb.dart
    - lib/base/networking/apis/tumdev/campus_backend.pbenum.dart
    - lib/base/networking/apis/tumdev/campus_backend.pbgrpc.dart
    - lib/base/networking/apis/tumdev/campus_backend.pbjson.dart
    - lib/base/networking/apis/google/protobuf/empty.pbjson.dart
    - lib/base/networking/apis/google/protobuf/timestamp.pb.dart