// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsK9MsOnQhQ0Vozvsm5BYproz75R6f2-0',
    appId: '1:37463514185:web:e73214376da5afac0f3398',
    messagingSenderId: '37463514185',
    projectId: 'tum-campus-app-test',
    authDomain: 'tum-campus-app-test.firebaseapp.com',
    storageBucket: 'tum-campus-app-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLk6HAS9VnZ5M6lQvMAZrfKjrPwihPC-g',
    appId: '1:37463514185:android:95c93d35f8e62cfd0f3398',
    messagingSenderId: '37463514185',
    projectId: 'tum-campus-app-test',
    storageBucket: 'tum-campus-app-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoZH1Kk11jRrvzzKgncc3vYoA6UOGhUyA',
    appId: '1:37463514185:ios:24e365da3f11ea9c0f3398',
    messagingSenderId: '37463514185',
    projectId: 'tum-campus-app-test',
    storageBucket: 'tum-campus-app-test.appspot.com',
    iosBundleId: 'de.tum.tca-flutter',
  );
}
