default_platform(:ios)

platform :ios do
    lane :beta do
        build_app(workspace: "Runner.xcworkspace", scheme: "Runner")

        api_key = app_store_connect_api_key(
            key_id: ENV["ASC_KEY_ID"],
            issuer_id: ENV["ASC_ISSUER_ID"],
            key_content: ENV["ASC_KEY"],
            is_key_content_base64: true,
        )

        upload_to_testflight(
            api_key: api_key,
            changelog: set_changelog(),
            skip_waiting_for_build_processing: true
        )
    end
end