const Map<String, String> degreeLongShort = {
  'Abschluß Sportlehrer i. freien Beruf': 'SL fr.Beruf',
  'Abschluß Studienkolleg': 'Stud.Kolleg',
  'Abschluss Studienkolleg (einsemestrig)': 'Stud.Kolleg (einsem.)',
  'Abschluss unbekannt': 'Unbekannt',
  'Aufbaustudium mit Abschlußzeugnis': 'Aufbaustud.',
  'Austauschprogramm (nicht studienbeitragspflichtig)': 'Austausch',
  'Austauschprogramm (Practical Project Students)': 'Austausch Praktikum',
  'Austauschprogramm (studienbeitragspflichtig)': 'Austausch',
  'Bachelor of Arts': 'B.A.',
  'Bachelor of Education / Berufliche Bildung': 'B.Ed. (bB)',
  'Bachelor of Education / Naturwissenschaftliche Bildung': 'B.Ed. (nB)',
  'Bachelor of Engineering in Chemical Engineering': 'B.Eng. CE',
  'Bachelor of Engineering in Electronics and Data Engineering': 'B.Eng. EDE',
  'Bachelor of Engineering with Honours in Chemical Engineering':
      'B.Eng. (hons) CE',
  'Bachelor of Engineering with Honours in Electronics and Data Engineering':
      'B.Eng. (hons) EDE',
  'Bachelor of Science': 'B.Sc.',
  'Berufliche Bildung: Erweiterung um ein Unterrichtsfach (Abschluss Zertifikat)':
      'Erweiterungsfach b. B.',
  'Brautechnische Fachprüfung': 'BT Fachprüf.',
  'Diplom - Berufspädagogik': 'Dipl.Be.päd.',
  'Diplom Arbeits-und Wirtschaftsw.- Aufbaustud.': 'Diplom AWA',
  'Diplom Fachhochschule': 'Diplom FH',
  'Diplom Managementorientiertes betriebsw.- Aufbaustudium': 'Diplom MbA',
  'Diplom Universität': 'Diplom Uni',
  'Diplom-Braumeister': 'Dipl.Braums.',
  'Doctor of Philosophy (Ph.D.)': 'Ph.D.',
  'Ergänzungs-/Vertiefungsstudium mit Zertifikat': 'Vertief.Zer.',
  'Ergänzungsstudium': 'Ergänz.stu.',
  'Fortführung der Immatrikulation nach erfolgreichem Abschluss':
      'Fortführung Immat',
  'Integrationsprogramm Ukraine ohne Abschluss': 'Ukraine',
  'Kein Abschluss': 'Kein Abschl.',
  'Master of Arts': 'M.A.',
  'Master of Business Administration': 'MBA',
  'Master of Education': 'M.Ed.',
  'Master of Education / Berufliche Bildung': 'M.Ed. (bB)',
  'Master of Education / Berufliche Bildung integriert':
      'M.Ed. (bB) integriert',
  'Master of Education / Naturwissenschaftliche Bildung': 'M.Ed. (nB)',
  'Master of Laws': 'LL.M.',
  'Master of Science': 'M.Sc.',
  'Master of Science (Elitestudium)': 'M.Sc. Elite',
  'Master of Science with Honours': 'M.Sc. Hon.',
  'Naturwissenschaftliche Bildung: Erweiterung um ein Unterrichtsfach (Abschluss Zertifikat)':
      'Erweiterungsfach n. B.',
  'Orientierungsstudium mit Teilnahmezertifikat': 'Orient.Zert.',
  'Promotion': 'Promotion',
  'Staatsexamen / 1. Staatsprüfung': 'Staatsexamen',
  'Staatsexamen / Lehramt an beruflichen Schulen': 'Staatsexamen',
  'Staatsexamen / Lehramt an beruflichen Schulen / Erweiterung oder Drittfach':
      'Staatsexamen',
  'Staatsexamen / Lehramt an Grundschulen': 'Staatsexamen',
  'Staatsexamen / Lehramt an Grundschulen / Erweiterung oder Drittfach':
      'Staatsexamen',
  'Staatsexamen / Lehramt an Gymnasien': 'Staatsexamen',
  'Staatsexamen / Lehramt an Gymnasien / Erweiterung oder Drittfach':
      'Staatsexamen',
  'Staatsexamen / Lehramt an Hauptschulen': 'Staatsexamen',
  'Staatsexamen / Lehramt an Hauptschulen / Erweiterung oder Drittfach':
      'Staatsexamen',
  'Staatsexamen / Lehramt an Mittelschulen': 'Staatsexamen',
  'Staatsexamen / Lehramt an Mittelschulen / Erweiterung oder Drittfach':
      'Staatsexamen',
  'Staatsexamen / Lehramt an Realschulen': 'Staatsexamen',
  'Staatsexamen / Lehramt an Realschulen / Erweiterung oder Drittfach':
      'Staatsexamen',
  'Staatsexamen / Lehramt an Sonderschulen': 'Staatsexamen',
  'Staatsexamen / Lehramt an Sonderschulen / Erweiterung oder Drittfach':
      'Staatsexamen',
  'Teilpromotion': 'Teilpromot.',
  'TopMath Promotion': 'TopMathProm.',
  'TUM Skills Excellence Program mit Zertifikat': 'TUM Skills Exc. Program',
  'Zertifikat über die Teilnahme am Integrationsprogramm': 'Ukraine',
};

const degreeIdShort = {
  "04": "Ph.D.",
  "05": "Ph.D",
  "06": "Ph.D",
  "07": "Ph.D",
  "14": "B.Ed.",
  "19": "B.Ed.",
  "16": "M.Sc.",
  "20": "M.Sc.",
  "28": "M.Sc.",
  "17": "B.Sc.",
  "18": "MBA",
  "29": "M.A.",
  "30": "B.A.",
  "37": "M.Ed.",
  "38": "M.Ed.",
  "39": "M.Ed.",
  "42": "M.Ed.",
  "53": "MBD",
  "60": "BECE",
  "61": "BEEDE",
};
