default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :beta do
    gradle(task: "clean bundle")
    
    upload_to_play_store(
      json_key_data: Base64.strict_decode64(ENV["GOOGLE_PLAY_SERVICE_ACCOUNT_KEY"]),
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "internal",
      release_status: "draft",
    )
  end
end
